### ISSUE TITLE
Premine documentation update

### ISSUE THREAD

**Issue by sneurlax** [ryo-currency/ryo-emergency#4]
Hello,

The current README.md refers to the Sumokoin premine figures

What are the total coin supply, emission rate, and premine figures for "Ryo"?

**Comment by fireice-uk** [comment]
This is still on the todo =)

Total emission is 80.18 million coins. Emission rate is unchanged.

We burned 8.7 million of the premine. 0.1 million was already spent and could not be recovered.

We might introduce a premine at or bellow 8.7 million in a future fork if the community approves.

**Comment by psychocrypt** [comment]
I added a short note to the README and linked our announcement https://github.com/ryo-currency/ryo-emergency/pull/6

**Comment by psychocrypt** [comment]
done in #6
